# Generated by Django 2.0.1 on 2018-07-27 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cells', models.ManyToManyField(related_name='_row_cells_+', through='django_dynamic_database.Cell', to='django_dynamic_database.Column')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='row',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='django_dynamic_database.Table'),
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='django_dynamic_database.Table'),
        ),
        migrations.AddField(
            model_name='cell',
            name='primary_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dynamic_database.Row'),
        ),
        migrations.AddField(
            model_name='cell',
            name='value_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dynamic_database.Column'),
        ),
    ]
